version: '3'
services:
  front:
    container_name: front
    build:
      context: ./front/
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: always
